@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.spyro.spyrosvillagers.crafting.recipe;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;