@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.spyro.spyrosvillagers.Entity.CustomVillager;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;