@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.spyro.spyrosvillagers.Entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;